export const searchListData = [
  { name: "apple", price: 1000, group: "fruits" },
  { name: "banana", price: 2000, group: "fruits" },
  { name: "orange", price: 3000, group: "fruits" },
  { name: "melon", price: 4000, group: "fruits" },
  { name: "watermelon", price: 5000, group: "fruits" },
  { name: "carrot", price: 1500, group: "vegetables" },
  { name: "potato", price: 1200, group: "vegetables" },
  { name: "onion", price: 1100, group: "vegetables" },
  { name: "broccoli", price: 2500, group: "vegetables" },
  { name: "cucumber", price: 1300, group: "vegetables" },
  { name: "beef", price: 7000, group: "meats" },
  { name: "chicken", price: 6000, group: "meats" },
  { name: "pork", price: 6500, group: "meats" },
  { name: "lamb", price: 8000, group: "meats" },
  { name: "fish", price: 5000, group: "meats" },
  { name: "milk", price: 1200, group: "dairy" },
  { name: "cheese", price: 4000, group: "dairy" },
  { name: "yogurt", price: 2500, group: "dairy" },
  { name: "butter", price: 3000, group: "dairy" },
  { name: "cream", price: 3500, group: "dairy" },
];
