export const ROUTE = {
  HOME: "/",
  INPUT_HOOK_EXAMPLE: "/input-hook-example",
  INPUT_HOOK_EXAMPLE2: "/input-hook-example2",
  TITLE_HOOK_EXAMPLE: "/title-hook-example",
  CLICK_HOOK_EXAMPLE: "/click-hook-example",
  CONFIRM_HOOK_EXAMPLE: "/confirm-hook-example",
  PREVENT_LEAVE_HOOK_EXAMPLE: "/prevent-leave-hook-example",
  BEFORE_LEAVE_EXAMPLE: "/before-leave-example",
  FADE_IN_HOOK_EXAMPLE: "/fade-in-hook-example",
  IMAGE_HOOK_EXAMPLE: "/image-hook-example",
  NETWORK_HOOK_EXAMPLE: "/network-hook-example",
  SCROLL_HOOK_EXAMPLE: "/scroll-hook-example",
  FULL_SCREEN_HOOK_EXAMPLE: "/full-screen-hook-example",
  NOTIFICATION_EXAMPLE: "/notification-example",
  AXIOS_HOOK_EXAMPLE: "/axios-example",
  SEARCH_HOOK_EXAMPLE: "/search-hook-example",
};
